Metrics/LineLength:
  Max: 120

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

AllCops:
  TargetRubyVersion: 2.2

# long script methods
Metrics/MethodLength:
  Enabled: false
